f = @(x) x.^2 .* cos(2 .* x) + 1;
f_3 = @(x) sin(2 .* x) .* (8 .* x.^2 - 12) - 24 .* x .* cos(2 .* x);

a = 0; b = 3; step = 0.01; errors = zeros(3, 301);
x = a : step : b;
y = f(x);

subplot(2, 2, 1);
n = 3;
p0 = plot(x, y, 'LineWidth', 2, 'Color', 'r');
grid on;
xlabel('x');
ylabel('y');
title('x^2*cos(2x)+1 and newton polynominal');
hold on;
fileID = fopen('data1.txt', 'r');
formatSpec = '%f %f';
sizeA = [2 Inf];
A = fscanf(fileID, formatSpec, sizeA);
fclose(fileID);
errors(1, 1:301) = abs(A(2, 1:301) - f(x));
p1 = plot(A(1, 1:301), A(2, 1:301), 'LineWidth', 2, 'Color', 'm');
nodes = 0 : 3 / n : 3;
plot(nodes, f(nodes), 'o', 'LineWidth', 2, 'Color', [0 0 0]);
legend([p0, p1], {'x^2 * cos(2x) + 1', 'n = 3'}, 'Location', 'northwest', 'FontSize', 12);

subplot(2, 2, 2);
n = 5;
p0 = plot(x, y, 'LineWidth', 2, 'Color', 'r');
grid on;
xlabel('x');
ylabel('y');
title('x^2*cos(2x)+1 and newton polynominal');
hold on;
fileID = fopen('data2.txt', 'r');
formatSpec = '%f %f';
sizeA = [2 Inf];
A = fscanf(fileID, formatSpec, sizeA);
fclose(fileID);
errors(2, 1:301) = abs(A(2, 1:301) - f(x));
p1 = plot(A(1, 1:301), A(2, 1:301), 'LineWidth', 2, 'Color', 'c');
nodes = 0 : 3 / n : 3;
plot(nodes, f(nodes), 'o', 'LineWidth', 2, 'Color', [0 0 0]);
legend([p0, p1], {'x^2 * cos(2x) + 1', 'n = 5'}, 'Location', 'northwest', 'FontSize', 12);

subplot(2, 2, [3 4]);
n = 7;
p0 = plot(x, y, 'LineWidth', 2, 'Color', 'r');
grid on;
xlabel('x');
ylabel('y');
title('x^2*cos(2x)+1 and newton polynominal');
hold on;
fileID = fopen('data3.txt', 'r');
formatSpec = '%f %f';
sizeA = [2 Inf];
A = fscanf(fileID, formatSpec, sizeA);
fclose(fileID);
errors(3, 1:301) = abs(A(2, 1:301) - f(x));
p1 = plot(A(1, 1:301), A(2, 1:301), 'LineWidth', 2, 'Color', 'g');
nodes = 0 : 3 / n : 3;
plot(nodes, f(nodes), 'o', 'LineWidth', 2, 'Color', [0 0 0]);
legend([p0, p1], {'x^2 * cos(2x) + 1', 'n = 7'}, 'Location', 'eastoutside', 'FontSize', 12);

figure;
n = 3;
subplot(2, 2, [1 2]);
p0 = plot(x, errors(1, 1:301), 'LineWidth', 2, 'Color', 'r');
grid on;
xlabel('x');
ylabel('absolute error');
title('absolute error: n = 3');
hold on;
nodes = 0 : 3 / n : 3;
plot(nodes, 0, 'o', 'LineWidth', 2, 'Color', [0 0 0]);
hold on;
w_3 = @(x) (x - nodes(1)) .* (x - nodes(2)) .*(x - nodes(3)) .*(x - nodes(4));
teor_error = ones(1, 301);
teor_error = teor_error * max(abs(f_3(x)));
teor_error = teor_error .* abs(w_3(x));
teor_error = teor_error / factorial(n);
p1 = plot(x, teor_error, 'LineWidth', 2, 'Color', 'g');
legend([p0 p1], {'absolute error', 'theoretical error'}, 'Location', 'eastoutside', 'FontSize', 12);

subplot(2, 2, 3);
n = 5;
plot(x, errors(2, 1:301), 'LineWidth', 2, 'Color', 'r');
grid on;
xlabel('x');
ylabel('absolute error');
title('absolute error: n = 5');
hold on;
nodes = 0 : 3 / n : 3;
plot(nodes, 0, 'o', 'LineWidth', 2, 'Color', [0 0 0]);

subplot(2, 2, 4);
n = 7;
plot(x, errors(3, 1:301), 'LineWidth', 2, 'Color', 'r');
grid on;
xlabel('x');
ylabel('absolute error');
title('absolute error: n = 7');
hold on;
nodes = 0 : 3 / n : 3;
plot(nodes, 0, 'o', 'LineWidth', 2, 'Color', [0 0 0]);

figure;
fileID = fopen('dependence.txt', 'r');
formatSpec = '%f %f';
sizeA = [2 Inf];
A = fscanf(fileID, formatSpec, sizeA);
fclose(fileID);
semilogy(A(1, 1:98), A(2, 1:98), 'LineWidth', 2, 'Color', 'm');
grid on;
xlabel('power of polynominal');
ylabel('max absolute error on [0; 3]');
title('Dependence between power of polynominal and error');
